//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CADisplayLink, UIScrollView;

@interface _PUICCrownInputInertialScroller : NSObject
{
    UIScrollView *_scrollView;
    CADisplayLink *_displayLink;
    double _inertialVelocity;
    double _brakeCoefficient;
    struct _RunningAverage *_runningAverageRotationalVelocity;
    double _enqueuedRotationalDelta;
    double _lastUpdateTime;
    double _crownInputSuppressionTime;
}

- (void).cxx_destruct;
- (void)_displayLinkFired:(id)arg1;
- (void)_wheelChangedWithEvent:(id)arg1;
- (void)dealloc;
- (id)initWithScrollView:(id)arg1;

@end

