//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface ORBWindowScaler : NSObject
{
    NSArray *_scalingViews;
    double _topWindowLevel;
    float _scale;
    float _presentedScale;
}

+ (id)sharedScaler;
- (void).cxx_destruct;
- (void)_setScale:(float)arg1 duration:(double)arg2 completion:(CDUnknownBlockType)arg3;
- (void)setDefaultScaleWithRubberBanding:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)setScale:(float)arg1 completion:(CDUnknownBlockType)arg2;
- (void)setupScalingWindows;
- (void)setCustomViewForScaling:(id)arg1;
@property(readonly, nonatomic) double topWindowLevel;
- (id)init;

@end

