//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIView;

@interface ORBWindowScaler : NSObject
{
    float _scale;
    float _presentedScale;
    UIView *_scalingView;
    CDUnknownBlockType _duration;
}

+ (id)sharedScaler;
@property(copy, nonatomic) CDUnknownBlockType duration; // @synthesize duration=_duration;
@property(nonatomic) __weak UIView *scalingView; // @synthesize scalingView=_scalingView;
- (void).cxx_destruct;
- (void)_setDefaultDuration;
- (void)_setScale:(float)arg1 duration:(double)arg2 completion:(CDUnknownBlockType)arg3;
- (void)setDefaultScaleWithRubberBanding:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)setScale:(float)arg1 completion:(CDUnknownBlockType)arg2;
- (id)init;

@end

