//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "PUICDictationViewControllerDelegate.h"
#import "PUICQuickboardViewControllerDelegate.h"

@class NSArray, NSAttributedString, NSFileHandle, NSString, PUICHighlightingView, PUICPlaceholderTextView, UIButton, UIGestureRecognizer, UIImage, UIImageView, UIScrollView, UIView;

@interface PUICQuickboardCompositionViewController : UIViewController <PUICQuickboardViewControllerDelegate, PUICDictationViewControllerDelegate>
{
    UIView *_referenceView;
    UIScrollView *_scrollView;
    UIView *_containerView;
    PUICHighlightingView *_recipientsContainer;
    PUICPlaceholderTextView *_recipientsTextView;
    PUICHighlightingView *_messageContainer;
    PUICPlaceholderTextView *_messageTextView;
    UIButton *_cancelButton;
    UIButton *_sendButton;
    UIGestureRecognizer *_recipientsFieldSelectionRecognizer;
    _Bool _needsContentRevealedOnQuickboardDismissal;
    _Bool _prefersStatusBarHidden;
    NSString *_originalTitle;
    UIImage *_audioRecordingImage;
    UIImageView *_backgroundImageView;
    _Bool _areRecipientsEditable;
    _Bool _shouldHideRecipients;
    _Bool _confirmSend;
    id <PUICQuickboardCompositionViewControllerDelegate> _delegate;
    NSArray *_recipients;
    NSArray *_recentContacts;
    NSArray *_textOptions;
    NSString *_animatedEmojiName;
    long long _bodyDictationMode;
    NSFileHandle *_audioRecording;
}

+ (id)composerWithRecipients:(id)arg1 message:(id)arg2;
@property(retain, nonatomic) NSFileHandle *audioRecording; // @synthesize audioRecording=_audioRecording;
@property(nonatomic) long long bodyDictationMode; // @synthesize bodyDictationMode=_bodyDictationMode;
@property(copy, nonatomic) NSString *animatedEmojiName; // @synthesize animatedEmojiName=_animatedEmojiName;
@property(nonatomic) _Bool confirmSend; // @synthesize confirmSend=_confirmSend;
@property(nonatomic) _Bool shouldHideRecipients; // @synthesize shouldHideRecipients=_shouldHideRecipients;
@property(nonatomic) _Bool areRecipientsEditable; // @synthesize areRecipientsEditable=_areRecipientsEditable;
@property(copy, nonatomic) NSArray *textOptions; // @synthesize textOptions=_textOptions;
@property(copy, nonatomic) NSArray *recentContacts; // @synthesize recentContacts=_recentContacts;
@property(copy, nonatomic) NSArray *recipients; // @synthesize recipients=_recipients;
@property(nonatomic) __weak id <PUICQuickboardCompositionViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)prefersStatusBarHidden;
@property(copy, nonatomic) NSAttributedString *message;
- (id)messageAttributes;
- (void)updateRecipientsLabel;
- (void)dictationViewController:(id)arg1 didFinishWithAudioFile:(id)arg2;
- (id)imageForAudioFile:(id)arg1 width:(double)arg2;
- (double)quickboard:(id)arg1 selectionFrameOriginYInDestinationView:(id *)arg2;
- (void)quickboardInputCancelled:(id)arg1;
- (void)quickboard:(id)arg1 textEntered:(id)arg2;
- (void)dismissQuickboardWithCompletion:(CDUnknownBlockType)arg1;
- (void)presentMessageQuickboardAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)sendButtonTapped;
- (void)cancelButtonTapped;
- (void)updateSendButtonState;
- (void)toggleHighlight:(id)arg1;
- (void)addGestureRecognizers;
- (void)unhighlightButton:(id)arg1;
- (void)highlightButton:(id)arg1;
- (void)_contentSizeCategoryDidChange:(id)arg1;
- (void)addConstraints;
- (void)loadView;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)presentFromViewController:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)setPrefersStatusBarHidden;
- (id)backgroundImageView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

