//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSError, NSFileHandle, NSString, PUICDictationViewController, UIImage;

@protocol PUICDictationViewControllerDelegate <NSObject>

@optional
- (void)dictationViewController:(PUICDictationViewController *)arg1 dictationFailedWithError:(NSError *)arg2;
- (void)dictationViewController:(PUICDictationViewController *)arg1 didRecognizeTranscriptionObjects:(NSArray *)arg2 languageModel:(NSString *)arg3;
- (void)dictationViewController:(PUICDictationViewController *)arg1 didFinishWithAudioFile:(NSFileHandle *)arg2;
- (UIImage *)imageForAudioFile:(NSFileHandle *)arg1 width:(double)arg2;
@end

