//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PUICStatusViewMutableState.h"

@class NSString, UIView;

@interface PUICSimpleStatusViewState : NSObject <PUICStatusViewMutableState>
{
    NSString *_stateName;
    UIView *_indicatorView;
    _Bool _statusViewStateActive;
    double _transitionInDuration;
    double _transitionOutDuration;
}

+ (id)simpleStateWithName:(id)arg1 withImage:(id)arg2;
@property(nonatomic) double transitionOutDuration; // @synthesize transitionOutDuration=_transitionOutDuration;
@property(nonatomic) double transitionInDuration; // @synthesize transitionInDuration=_transitionInDuration;
@property(nonatomic, getter=statusViewIsStateActive) _Bool statusViewStateActive; // @synthesize statusViewStateActive=_statusViewStateActive;
- (void).cxx_destruct;
- (double)statusViewTransitionOutDuration;
- (double)statusViewTransitionInDuration;
- (id)statusViewIndicatorView;
- (id)statusViewStateName;
- (id)initWithName:(id)arg1 indicatorView:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

